### ISSUE TITLE
[BUG] Linked frames do not fade all others linked to same frame

### ISSUE THREAD

**Issue by HyenaHorror** [PhenomDevel/BlizzHUDTweaks#25]
#### Description
Linked frames do not always show at the same time. After linking several frames they only appear when hovering the primary link.

#### Steps to Reproduce
1. Open Mouseover Fading options
2. Select frame links
3. Link many frames to ActionBar1 (for example). I included ActionBar2, Player Frame, Buff Frame, Debuff Frame.
4. Hover over each item linked.

#### Expectation
I expected hovering over a linked frame (e.g. Player Frame) to fade all others linked to ActionBar1. Linked frames only fade when hovering ActionBar1.

If this is the intended function, I would greatly appreciate an option to cascade or copy links to other frames while editing options.

#### Video demonstration
https://youtu.be/XZbXsLK4IBM

**Comment by PhenomDevel** [comment]
In the current iteration this is intended behavior since I didn't want to automatically cascade all settings for each selected frame. Nevertheless, I am thinking of a scenario where you would want to select a lot of frames on for example actionbar1 and not want all other linked frames to also reveal the full link group.

So actually the behavior you showed in the video. I'm thinking of always cascading the options down, because this seems to be the more reasonable approach.

**Comment by PhenomDevel** [comment]
I also believe this behaviour would be more like the description states it should be... My only concern is that it is not clear for the average user.

**Comment by HyenaHorror** [comment]
Perhaps a grouping system could be added with separate labels. They could be distinguished as "link to frame" and "link to group". The former would only occur when the primary link is hovered, while the latter could check each group to see if the hovered element is present. I'm not sure how that might affect performance though.

**Comment by PhenomDevel** [comment]
Yeah i thought about this idea. I didn't want to go this route since it adds more work and more complexicity. I added the syncing by default for `1.26.X-beta`. Since the feature is new i'd go this route and see if it is used at all and if the behaviour is in any way problematic.

**Comment by PhenomDevel** [comment]
Feature is available in `1.26.7`. Will be syncing by default for now.
