### ISSUE TITLE
Hide Chat, bag, and system icons.

### ISSUE THREAD

**Issue by SirStreetguru** [PhenomDevel/BlizzHUDTweaks#38]
I play on an OLED TV, so for safety I periodically hide the UI with a hot key, I thought this addon could solve that issue for me, however mini-map icons are still around, as well as the whole chat frame, and the system/bag icons on the bottom left. 

Would be great if we could have control over those as well. 

Having an option to just eliminate the chat background would be preferred, so chat would turn more into floating text.

**Comment by PhenomDevel** [comment]
If you use the wow buld in function to hide the UI everything should be hidden. Atleast that's how it works for me.

If not the problem comes from another addon.

I don't want to add the chat frame as fadeable frame since it is really complicated and i don't want to bother with that. Same for the minimap icons. It is not as easy as a lot of the other frames.

For bag and system try  there area options to fade those and it should work like all the other frames.

**Comment by Rezy942** [comment]
> I play on an OLED TV, so for safety I periodically hide the UI with a hot key, I thought this addon could solve that issue for me, however mini-map icons are still around, as well as the whole chat frame, and the system/bag icons on the bottom left.
> 
> Would be great if we could have control over those as well.
> 
> Having an option to just eliminate the chat background would be preferred, so chat would turn more into floating text.

Try addon "BasicChatMods" it is perfect for fading of chat while being lightweight. It is unfortunate though that we have to use a million of addons all doing separate things. But oh well.
