### ISSUE TITLE
FEATURE: Expand "Hide Unused action bar 1 buttons"

### ISSUE THREAD

**Issue by luiscarlos92** [PhenomDevel/BlizzHUDTweaks#40]
Hi. I love your addon, using it mainly for the conditionals that allow to hide the action bars in so many different cases.

Came across the option of Hide Unused action bar 1 buttons and I would love if that options was not only for bar 1, but toggable for each action bar.

Thank you

**Comment by Rezy942** [comment]
+1 to this. but please fix the weight graphic bug behind action bar 1 when using this feature

**Comment by PhenomDevel** [comment]
For each action bar except action bar 1 you can do it with the default ui. So there is no need for me to implement it.

@Rezy942 I have no clue what you mean.. Could you explain it?

**Comment by Rezy942** [comment]
![image](https://user-images.githubusercontent.com/122007087/211347026-5f2b5227-04af-4b56-8a30-40c545d250ee.png)
This is what happens when I click hide unused buttons through this addon, while having blizzard art bar enabled

Also regarding this thread, you mentioned its in the default UI. Could you direct us to that?
I tried unchecking "always show buttons" in edit mode of action bars 2 and up, but that doesnt seem to do anything.

Thank you

**Comment by PhenomDevel** [comment]
This should be fixed in 1.30.4

**Comment by Rezy942** [comment]
Works like a charm! Thanks!
Regarding this thread - can you comment on how to hide unused bars for action bars 2, 3, and so on?
You mentioned you can in blizz UI, but i couldnt find it anywhere
![image](https://user-images.githubusercontent.com/122007087/211544579-5e0ea01f-d76b-4803-8f5e-5e390aaf2c9c.png)

**Comment by PhenomDevel** [comment]
Oh yeah forgot about that... 

I simply uncheck `always show buttons` ... Note that this will only take effect after a reaload properly.

**Comment by Rezy942** [comment]
Not sure what kept happening before when I was unchecking it, I guess i had to reload.
Works great now, thank you so much!!
![image](https://user-images.githubusercontent.com/122007087/211545682-dabd6740-ee16-43f6-8617-8e411d4e6e4c.png)
